version: '3.8'

services:
  images-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elastika-images
    hostname: images-server
    restart: unless-stopped
    environment:
      PORT: 3500
      NODE_ENV: production
      IMAGES_DIR: /var/www/images
      API_KEY: ${IMAGES_API_KEY:-mathidev369}
      PUBLIC_URL: ${PUBLIC_URL:-http://86.48.26.221:3500}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-20}
      VERSION: 1.0.0
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.1,172.16.0.0/12}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://86.48.26.221:3000,http://86.48.26.221:3002}
    ports:
      - "${HOST_PORT:-3500}:3500"
    volumes:
      # Directorio de imágenes persistente
      - images_data:/var/www/images
      # Logs (opcional)
      - ./logs:/app/logs
    networks:
      - elastika-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3500/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Volúmenes persistentes
volumes:
  images_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/images

# Red personalizada
networks:
  elastika-network:
    external: true