version: '3.8'

services:
  images-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elastika-images-backend
    hostname: images-server
    restart: unless-stopped
    environment:
      PORT: 3500
      NODE_ENV: production
      IMAGES_DIR: /var/www/images
      API_KEY: ${IMAGES_API_KEY:-mathidev369}
      PUBLIC_URL: ${PUBLIC_URL:-http://86.48.26.221}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-20}
      VERSION: 1.0.0
      TRUSTED_PROXIES: "172.16.0.0/12,10.0.0.0/8,127.0.0.1,172.19.0.0/16"
      ALLOWED_ORIGINS: "*"
    expose:
      - "3500"  # Solo interno
    volumes:
      - images_data:/var/www/images
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - elastika-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3500/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  images_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/images

networks:
  elastika-network:
    external: true
